spring.application.name=chat
#spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.model=gpt-4o-mini
spring.ai.ollama.init.pull-model-strategy=when_missing
spring.ai.ollama.chat.model=hf.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF
spring.application.cli=true